services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes", "--protected-mode", "no"]
    volumes:
      - /local-data/:/data
  
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - 8001:5540
    depends_on:
      - redis
    volumes:
      - redisinsight-data:/db

  broker:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674
    command: >
      sh -c "
      rabbitmq-plugins enable rabbitmq_stomp &&
      rabbitmq-plugins enable rabbitmq_web_stomp &&
      rabbitmq-server"
  backend:
    build:
      context: ./Backend/server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - broker
    environment:
      - RABBITMQ_HOST=broker
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 4322:4321
    depends_on:
      - backend
    environment:
      - BACKEND_HOST=backend
      - RABBITMQ_HOST=localhost
volumes:
  redisinsight-data: