services:
  broker:
    image: futscoresbroker
    build:
      context: ./Backend/broker
      dockerfile: Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674
  backend:
    image: futscoresbackend
    build:
      context: ./Backend/server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - broker
    environment:
      - RABBITMQ_HOST=broker
  frontend:
    image: futscoresfrontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 4321:4321
    depends_on:
      - backend
    environment:
      - BACKEND_HOST=backend
      - RABBITMQ_HOST=localhost
